server:
  port: 8081

spring:
  application:
    name: spring-boot-resiliency4j

# Resilience4j circuit breaker configuration for the external dummyjson API
resilience4j:
  circuitbreaker:
    instances:
      dummyjson:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
